repos:
-   repo: local
    hooks:
    -   id: ansible-lint
        name: Ansible Lint
        entry: ./runner.sh ansible-lint
        language: script
        files: \.(yaml|yml)$

    -   id: ansible-syntax-check
        name: Ansible Syntax Check
        entry: ./runner.sh ansible-playbook site.yml --syntax-check
        language: script
        files: \.(yaml|yml)$
